### Unique Install Scripts ###
apt-get install -y libicu-dev
apt-get install -y zlib1g-dev
apt-get install -y make
apt-get install -y libcurl4-openssl-dev
apt-get install -y libssl-dev
apt-get install -y libfontconfig1-dev
apt-get install -y libfreetype6-dev
apt-get install -y libfribidi-dev
apt-get install -y libharfbuzz-dev
apt-get install -y libjpeg-dev
apt-get install -y libpng-dev
apt-get install -y libtiff-dev
apt-get install -y pandoc
apt-get install -y libxml2-dev
apt-get install -y cmake
apt-get install -y git
apt-get install -y libgit2-dev
apt-get install -y libglpk-dev
apt-get install -y libgmp3-dev
apt-get install -y python3
apt-get install -y libgdal-dev
apt-get install -y gdal-bin
apt-get install -y libgeos-dev
apt-get install -y libproj-dev
apt-get install -y libsqlite3-dev
apt-get install -y default-jdk
apt-get install -y imagemagick
apt-get install -y libmagick++-dev
apt-get install -y gsfonts
apt-get install -y texlive
